server:
 port: 7070
 
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: postgres
    password: postgres
    driver: 
      class: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:/db/dbchangeLog.xml
  jpa:
    hibernate:
      ddl-auto: none