server:
  port: 6000
  servlet:
    context-path: /dbtest

spring:
  application:
    name: dbtest
  datasource:
    usuario:
      url: jdbc:postgresql://localhost:5432/usuario
      username: postgres
      password: postgres
      driver: 
       class: org.hibernate.dialect.PostgreSQL10Dialect
    endereco:
      url: jdbc:postgresql://localhost:5432/endereco
      username: postgres
      password: postgres
      driver: 
        class: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
        change-log: classpath:/db/usuario/liquibase-changeLog.xml

dbtest:
  endereco:
    liquibase:
      change-log: classpath:/db/endereco/liquibase-changeLog.xml